"""initial core schema

Revision ID: 796b2c35b506
Revises: 
Create Date: 2026-09-05 14:45:14.831543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '796b2c35b506'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('min_risk_score', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('max_risk_score', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('required_role', sa.Enum('ADMIN', 'SALES_REP', 'SALES_MANAGER', 'FINANCE', 'CUSTOMER', name='user_role'), nullable=False),
    sa.Column('approval_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('approval_order >= 1', name='ck_approval_rules_order'),
    sa.CheckConstraint('max_risk_score IS NULL OR max_risk_score >= min_risk_score', name='ck_approval_rules_score_band'),
    sa.CheckConstraint('min_risk_score >= 0', name='ck_approval_rules_min_score'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('min_risk_score', 'required_role', 'approval_order', name='uq_approval_rule_step')
    )
    op.create_index('ix_approval_rules_active', 'approval_rules', ['is_active'], unique=False)
    op.create_table('business_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index('ix_business_settings_key', 'business_settings', ['key'], unique=True)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('company', sa.String(length=150), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('customer_tier', sa.Enum('BRONZE', 'SILVER', 'GOLD', name='customer_tier'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_customers_email', 'customers', ['email'], unique=True)
    op.create_index('ix_customers_tier', 'customers', ['customer_tier'], unique=False)
    op.create_table('discount_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('scope', sa.Enum('CUSTOMER_TIER', 'PRODUCT_CATEGORY', name='discount_rule_scope'), nullable=False),
    sa.Column('customer_tier', sa.Enum('BRONZE', 'SILVER', 'GOLD', name='customer_tier'), nullable=True),
    sa.Column('product_category', sa.String(length=80), nullable=True),
    sa.Column('max_discount_percent', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("(scope = 'CUSTOMER_TIER' AND customer_tier IS NOT NULL AND product_category IS NULL) OR (scope = 'PRODUCT_CATEGORY' AND product_category IS NOT NULL AND customer_tier IS NULL)", name='ck_discount_rules_scope_target'),
    sa.CheckConstraint('max_discount_percent >= 0 AND max_discount_percent <= 100', name='ck_discount_rules_percent_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'customer_tier', 'product_category', name='uq_discount_rule_target')
    )
    op.create_index('ix_discount_rules_active', 'discount_rules', ['is_active'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('billing_frequency', sa.Enum('MONTHLY', 'QUARTERLY', 'YEARLY', name='billing_frequency'), nullable=False),
    sa.Column('billing_interval', sa.Integer(), nullable=False),
    sa.Column('proration_enabled', sa.Boolean(), nullable=False),
    sa.Column('cancellation_rule', sa.Enum('IMMEDIATE', 'END_OF_PERIOD', name='cancellation_rule'), nullable=False),
    sa.Column('refund_rule', sa.Enum('NONE', 'PRORATED', 'FULL', name='refund_rule'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('billing_interval >= 1', name='ck_subscription_plans_interval'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_subscription_plans_active', 'subscription_plans', ['is_active'], unique=False)
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('shipping_cost_weight', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('shipping_cost_weight >= 0', name='ck_warehouses_weight_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_warehouses_active', 'warehouses', ['is_active'], unique=False)
    op.create_table('price_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('customer_tier', sa.Enum('BRONZE', 'SILVER', 'GOLD', name='customer_tier'), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_price_lists_active', 'price_lists', ['is_active'], unique=False)
    op.create_index('ix_price_lists_customer_id', 'price_lists', ['customer_id'], unique=False)
    op.create_index('ix_price_lists_tier', 'price_lists', ['customer_tier'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('product_type', sa.Enum('ONE_TIME', 'RECURRING', 'SERVICE', name='product_type'), nullable=False),
    sa.Column('default_subscription_plan_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('cost_price >= 0', name='ck_products_cost_non_negative'),
    sa.CheckConstraint('price >= 0', name='ck_products_price_non_negative'),
    sa.CheckConstraint('tax_rate >= 0 AND tax_rate <= 100', name='ck_products_tax_rate_range'),
    sa.ForeignKeyConstraint(['default_subscription_plan_id'], ['subscription_plans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index('ix_products_active', 'products', ['is_active'], unique=False)
    op.create_index('ix_products_category', 'products', ['category'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'SALES_REP', 'SALES_MANAGER', 'FINANCE', 'CUSTOMER', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_customer_id', 'users', ['customer_id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('available_quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('available_quantity >= 0', name='ck_inventory_available_non_negative'),
    sa.CheckConstraint('reserved_quantity <= available_quantity', name='ck_inventory_reserved_within_available'),
    sa.CheckConstraint('reserved_quantity >= 0', name='ck_inventory_reserved_non_negative'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'product_id', name='uq_inventory_warehouse_product')
    )
    op.create_index('ix_inventory_product_id', 'inventory', ['product_id'], unique=False)
    op.create_table('product_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('attribute', sa.String(length=60), nullable=False),
    sa.Column('value', sa.String(length=80), nullable=False),
    sa.Column('extra_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sku', sa.String(length=60), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'attribute', 'value', name='uq_variant_product_attr_value'),
    sa.UniqueConstraint('sku')
    )
    op.create_index('ix_product_variants_product_id', 'product_variants', ['product_id'], unique=False)
    op.create_table('quotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_number', sa.String(length=40), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('sales_rep_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'REVISION_REQUIRED', 'SENT', 'UNDER_NEGOTIATION', 'CONFIRMED', 'FULFILLMENT', 'COMPLETED', 'CANCELLED', name='quotation_status'), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cost_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('margin_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('margin_percent', sa.Numeric(precision=7, scale=3), nullable=False),
    sa.Column('recurring_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('one_time_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('order_discount_percent', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('risk_level', sa.Enum('NORMAL', 'MODERATE', 'HIGH', name='risk_level'), nullable=False),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('approval_cycle', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('order_discount_percent >= 0 AND order_discount_percent <= 100', name='ck_quotations_order_discount_range'),
    sa.CheckConstraint('risk_score >= 0', name='ck_quotations_risk_score_non_negative'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_rep_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_number')
    )
    op.create_index('ix_quotations_customer_id', 'quotations', ['customer_id'], unique=False)
    op.create_index('ix_quotations_last_activity_at', 'quotations', ['last_activity_at'], unique=False)
    op.create_index('ix_quotations_quote_number', 'quotations', ['quote_number'], unique=True)
    op.create_index('ix_quotations_sales_rep_id', 'quotations', ['sales_rep_id'], unique=False)
    op.create_index('ix_quotations_status', 'quotations', ['status'], unique=False)
    op.create_table('recommendation_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_product_id', sa.Integer(), nullable=False),
    sa.Column('recommended_product_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_type', sa.Enum('UPSELL', 'CROSS_SELL', name='recommendation_type'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('promotion_active', sa.Boolean(), nullable=False),
    sa.Column('minimum_margin_percent', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('source_product_id <> recommended_product_id', name='ck_recommendation_distinct_products'),
    sa.ForeignKeyConstraint(['recommended_product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_product_id', 'recommended_product_id', 'recommendation_type', name='uq_recommendation_pair')
    )
    op.create_index('ix_recommendation_rules_source', 'recommendation_rules', ['source_product_id'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('approval_rule_id', sa.Integer(), nullable=True),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('cycle', sa.Integer(), nullable=False),
    sa.Column('required_role', sa.Enum('ADMIN', 'SALES_REP', 'SALES_MANAGER', 'FINANCE', 'CUSTOMER', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'RETURNED', 'SKIPPED', name='approval_status'), nullable=False),
    sa.Column('acted_by_id', sa.Integer(), nullable=True),
    sa.Column('acted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('risk_score_snapshot', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('risk_level_snapshot', sa.Enum('NORMAL', 'MODERATE', 'HIGH', name='risk_level'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('cycle >= 1', name='ck_approvals_cycle'),
    sa.CheckConstraint('step_order >= 1', name='ck_approvals_step_order'),
    sa.ForeignKeyConstraint(['acted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['approval_rule_id'], ['approval_rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quotation_id', 'cycle', 'step_order', name='uq_approval_step_per_cycle')
    )
    op.create_index('ix_approvals_quotation_id', 'approvals', ['quotation_id'], unique=False)
    op.create_index('ix_approvals_required_role', 'approvals', ['required_role'], unique=False)
    op.create_index('ix_approvals_status', 'approvals', ['status'], unique=False)
    op.create_table('deal_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.Enum('STALLED_DEAL', 'DISCOUNT_ANOMALY', 'DELIVERY_SLIPPAGE', name='alert_type'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='alert_severity'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'ESCALATED', 'RESOLVED', name='alert_status'), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('sales_rep_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('acknowledged_by_id', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sales_rep_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deal_alerts_quotation_id', 'deal_alerts', ['quotation_id'], unique=False)
    op.create_index('ix_deal_alerts_status', 'deal_alerts', ['status'], unique=False)
    op.create_index('ix_deal_alerts_type', 'deal_alerts', ['alert_type'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=40), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'PARTIALLY_PAID', 'PAID', 'CANCELLED', name='invoice_status'), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('balance_due', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('paid_amount >= 0', name='ck_invoices_paid_non_negative'),
    sa.CheckConstraint('total_amount >= 0', name='ck_invoices_total_non_negative'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index('ix_invoices_customer_id', 'invoices', ['customer_id'], unique=False)
    op.create_index('ix_invoices_invoice_number', 'invoices', ['invoice_number'], unique=True)
    op.create_index('ix_invoices_quotation_id', 'invoices', ['quotation_id'], unique=False)
    op.create_index('ix_invoices_status', 'invoices', ['status'], unique=False)
    op.create_table('price_list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price_list_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_variant_id', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('min_quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('min_quantity >= 1', name='ck_price_list_items_min_quantity'),
    sa.CheckConstraint('unit_price >= 0', name='ck_price_list_items_price_non_negative'),
    sa.ForeignKeyConstraint(['price_list_id'], ['price_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('price_list_id', 'product_id', 'product_variant_id', 'min_quantity', name='uq_price_list_item_scope')
    )
    op.create_index('ix_price_list_items_product_id', 'price_list_items', ['product_id'], unique=False)
    op.create_table('quotation_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_variant_id', sa.Integer(), nullable=True),
    sa.Column('subscription_plan_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('product_category', sa.String(length=80), nullable=False),
    sa.Column('billing_type', sa.Enum('ONE_TIME', 'RECURRING', name='billing_type'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('requested_discount_percent', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('allowed_discount_percent', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('excess_discount_percent', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('line_subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_discount_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_tax_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_cost_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_margin_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_margin_percent', sa.Numeric(precision=7, scale=3), nullable=False),
    sa.Column('added_from_recommendation', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('quantity >= 1', name='ck_quotation_items_quantity'),
    sa.CheckConstraint('requested_discount_percent >= 0 AND requested_discount_percent <= 100', name='ck_quotation_items_requested_discount_range'),
    sa.CheckConstraint('unit_price >= 0', name='ck_quotation_items_unit_price'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_plan_id'], ['subscription_plans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quotation_items_product_id', 'quotation_items', ['product_id'], unique=False)
    op.create_index('ix_quotation_items_quotation_id', 'quotation_items', ['quotation_id'], unique=False)
    op.create_table('backorders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('quotation_item_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('allocated_quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'PARTIALLY_ALLOCATED', 'ALLOCATED', 'CANCELLED', name='backorder_status'), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('allocated_quantity >= 0 AND allocated_quantity <= quantity', name='ck_backorders_allocated_within_quantity'),
    sa.CheckConstraint('quantity >= 1', name='ck_backorders_quantity'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quotation_item_id'], ['quotation_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_backorders_quotation_id', 'backorders', ['quotation_id'], unique=False)
    op.create_index('ix_backorders_status', 'backorders', ['status'], unique=False)
    op.create_table('fulfillment_splits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('quotation_item_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('allocated_quantity', sa.Integer(), nullable=False),
    sa.Column('estimated_shipping_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'RESERVED', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='fulfillment_status'), nullable=False),
    sa.Column('is_manual_override', sa.Boolean(), nullable=False),
    sa.Column('promised_delivery_date', sa.Date(), nullable=True),
    sa.Column('reserved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('allocated_quantity >= 1', name='ck_fulfillment_splits_quantity'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quotation_item_id'], ['quotation_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fulfillment_splits_quotation_id', 'fulfillment_splits', ['quotation_id'], unique=False)
    op.create_index('ix_fulfillment_splits_status', 'fulfillment_splits', ['status'], unique=False)
    op.create_index('ix_fulfillment_splits_warehouse_id', 'fulfillment_splits', ['warehouse_id'], unique=False)
    op.create_table('negotiations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('quotation_item_id', sa.Integer(), nullable=True),
    sa.Column('raised_by_id', sa.Integer(), nullable=False),
    sa.Column('negotiation_type', sa.Enum('COMMENT', 'CHANGE_REQUEST', 'COUNTER_DISCOUNT', name='negotiation_type'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_REVIEW', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', name='negotiation_status'), nullable=False),
    sa.Column('requested_discount_percent', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('triggered_reapproval', sa.Boolean(), nullable=False),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('requested_discount_percent IS NULL OR (requested_discount_percent >= 0 AND requested_discount_percent <= 100)', name='ck_negotiations_discount_range'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quotation_item_id'], ['quotation_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raised_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_negotiations_customer_id', 'negotiations', ['customer_id'], unique=False)
    op.create_index('ix_negotiations_quotation_id', 'negotiations', ['quotation_id'], unique=False)
    op.create_index('ix_negotiations_status', 'negotiations', ['status'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('BANK_TRANSFER', 'CARD', 'CASH', 'CHEQUE', 'UPI', 'OTHER', name='payment_method'), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='payment_status'), nullable=False),
    sa.Column('recorded_by_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_payments_amount_positive'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payments_invoice_id', 'payments', ['invoice_id'], unique=False)
    op.create_index('ix_payments_payment_date', 'payments', ['payment_date'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=True),
    sa.Column('quotation_item_id', sa.Integer(), nullable=True),
    sa.Column('subscription_plan_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'CANCELLED', 'EXPIRED', name='subscription_status'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('current_period_start', sa.Date(), nullable=True),
    sa.Column('current_period_end', sa.Date(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('quantity >= 1', name='ck_subscriptions_quantity'),
    sa.CheckConstraint('unit_price >= 0', name='ck_subscriptions_unit_price'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quotation_item_id'], ['quotation_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_plan_id'], ['subscription_plans.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_subscriptions_customer_id', 'subscriptions', ['customer_id'], unique=False)
    op.create_index('ix_subscriptions_status', 'subscriptions', ['status'], unique=False)
    op.create_table('billing_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('billing_date', sa.Date(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_proration', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'INVOICED', 'PAID', 'SKIPPED', 'CANCELLED', name='billing_schedule_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_billing_schedules_billing_date', 'billing_schedules', ['billing_date'], unique=False)
    op.create_index('ix_billing_schedules_status', 'billing_schedules', ['status'], unique=False)
    op.create_index('ix_billing_schedules_subscription_id', 'billing_schedules', ['subscription_id'], unique=False)
    op.create_table('negotiation_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negotiation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['negotiation_id'], ['negotiations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_negotiation_comments_negotiation_id', 'negotiation_comments', ['negotiation_id'], unique=False)
    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('quotation_item_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('billing_schedule_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('billing_type', sa.Enum('ONE_TIME', 'RECURRING', name='billing_type'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('quantity >= 1', name='ck_invoice_items_quantity'),
    sa.ForeignKeyConstraint(['billing_schedule_id'], ['billing_schedules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quotation_item_id'], ['quotation_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoice_items_invoice_id', 'invoice_items', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_invoice_items_invoice_id', table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index('ix_negotiation_comments_negotiation_id', table_name='negotiation_comments')
    op.drop_table('negotiation_comments')
    op.drop_index('ix_billing_schedules_subscription_id', table_name='billing_schedules')
    op.drop_index('ix_billing_schedules_status', table_name='billing_schedules')
    op.drop_index('ix_billing_schedules_billing_date', table_name='billing_schedules')
    op.drop_table('billing_schedules')
    op.drop_index('ix_subscriptions_status', table_name='subscriptions')
    op.drop_index('ix_subscriptions_customer_id', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('ix_payments_payment_date', table_name='payments')
    op.drop_index('ix_payments_invoice_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_negotiations_status', table_name='negotiations')
    op.drop_index('ix_negotiations_quotation_id', table_name='negotiations')
    op.drop_index('ix_negotiations_customer_id', table_name='negotiations')
    op.drop_table('negotiations')
    op.drop_index('ix_fulfillment_splits_warehouse_id', table_name='fulfillment_splits')
    op.drop_index('ix_fulfillment_splits_status', table_name='fulfillment_splits')
    op.drop_index('ix_fulfillment_splits_quotation_id', table_name='fulfillment_splits')
    op.drop_table('fulfillment_splits')
    op.drop_index('ix_backorders_status', table_name='backorders')
    op.drop_index('ix_backorders_quotation_id', table_name='backorders')
    op.drop_table('backorders')
    op.drop_index('ix_quotation_items_quotation_id', table_name='quotation_items')
    op.drop_index('ix_quotation_items_product_id', table_name='quotation_items')
    op.drop_table('quotation_items')
    op.drop_index('ix_price_list_items_product_id', table_name='price_list_items')
    op.drop_table('price_list_items')
    op.drop_index('ix_invoices_status', table_name='invoices')
    op.drop_index('ix_invoices_quotation_id', table_name='invoices')
    op.drop_index('ix_invoices_invoice_number', table_name='invoices')
    op.drop_index('ix_invoices_customer_id', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('ix_deal_alerts_type', table_name='deal_alerts')
    op.drop_index('ix_deal_alerts_status', table_name='deal_alerts')
    op.drop_index('ix_deal_alerts_quotation_id', table_name='deal_alerts')
    op.drop_table('deal_alerts')
    op.drop_index('ix_approvals_status', table_name='approvals')
    op.drop_index('ix_approvals_required_role', table_name='approvals')
    op.drop_index('ix_approvals_quotation_id', table_name='approvals')
    op.drop_table('approvals')
    op.drop_index('ix_recommendation_rules_source', table_name='recommendation_rules')
    op.drop_table('recommendation_rules')
    op.drop_index('ix_quotations_status', table_name='quotations')
    op.drop_index('ix_quotations_sales_rep_id', table_name='quotations')
    op.drop_index('ix_quotations_quote_number', table_name='quotations')
    op.drop_index('ix_quotations_last_activity_at', table_name='quotations')
    op.drop_index('ix_quotations_customer_id', table_name='quotations')
    op.drop_table('quotations')
    op.drop_index('ix_product_variants_product_id', table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index('ix_inventory_product_id', table_name='inventory')
    op.drop_table('inventory')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_customer_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_products_category', table_name='products')
    op.drop_index('ix_products_active', table_name='products')
    op.drop_table('products')
    op.drop_index('ix_price_lists_tier', table_name='price_lists')
    op.drop_index('ix_price_lists_customer_id', table_name='price_lists')
    op.drop_index('ix_price_lists_active', table_name='price_lists')
    op.drop_table('price_lists')
    op.drop_index('ix_warehouses_active', table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index('ix_subscription_plans_active', table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index('ix_discount_rules_active', table_name='discount_rules')
    op.drop_table('discount_rules')
    op.drop_index('ix_customers_tier', table_name='customers')
    op.drop_index('ix_customers_email', table_name='customers')
    op.drop_table('customers')
    op.drop_index('ix_business_settings_key', table_name='business_settings')
    op.drop_table('business_settings')
    op.drop_index('ix_approval_rules_active', table_name='approval_rules')
    op.drop_table('approval_rules')
    # ### end Alembic commands ###
