from enum import StrEnum


class UserRole(StrEnum):
    SALES_REP = "SALES_REP"
    SALES_MANAGER = "SALES_MANAGER"
    FINANCE = "FINANCE"
    OPERATIONS = "OPERATIONS"
    CUSTOMER = "CUSTOMER"
    ADMIN = "ADMIN"


class CustomerStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    ON_HOLD = "ON_HOLD"


class ProductType(StrEnum):
    ONE_TIME = "ONE_TIME"
    SUBSCRIPTION = "SUBSCRIPTION"
    SERVICE = "SERVICE"


class CategoryKind(StrEnum):
    HARDWARE = "HARDWARE"
    SERVICE = "SERVICE"
    SOFTWARE = "SOFTWARE"
    ACCESSORY = "ACCESSORY"
    SUBSCRIPTION = "SUBSCRIPTION"


class QuoteStatus(StrEnum):
    DRAFT = "DRAFT"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    NEGOTIATING = "NEGOTIATING"
    REJECTED = "REJECTED"
    CONFIRMED = "CONFIRMED"
    CANCELLED = "CANCELLED"


class ApprovalStatus(StrEnum):
    NOT_REQUIRED = "NOT_REQUIRED"
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"


class ApprovalStepStatus(StrEnum):
    WAITING = "WAITING"
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    SKIPPED = "SKIPPED"


class NegotiationStatus(StrEnum):
    NONE = "NONE"
    OPEN = "OPEN"
    COUNTERED = "COUNTERED"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    CLOSED = "CLOSED"


class NegotiationRequestType(StrEnum):
    DISCOUNT = "DISCOUNT"
    QUANTITY = "QUANTITY"
    PRODUCT_CHANGE = "PRODUCT_CHANGE"
    LINE_REJECT = "LINE_REJECT"
    ALTERNATIVE = "ALTERNATIVE"
    PAYMENT_TERMS = "PAYMENT_TERMS"
    COMMENT = "COMMENT"
    ACCEPT_RECOMMENDATION = "ACCEPT_RECOMMENDATION"
    COUNTEROFFER = "COUNTEROFFER"


class RequestStatus(StrEnum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    COUNTERED = "COUNTERED"
    CANCELLED = "CANCELLED"


class RiskLevel(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class HealthLevel(StrEnum):
    HEALTHY = "HEALTHY"
    WATCH = "WATCH"
    AT_RISK = "AT_RISK"
    CRITICAL = "CRITICAL"


class RecommendationType(StrEnum):
    UPSELL = "UPSELL"
    CROSS_SELL = "CROSS_SELL"
    ALTERNATIVE = "ALTERNATIVE"
    BUNDLE = "BUNDLE"


class Priority(StrEnum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class ReservationStatus(StrEnum):
    RESERVED = "RESERVED"
    RELEASED = "RELEASED"
    FULFILLED = "FULFILLED"


class OrderStatus(StrEnum):
    PENDING = "PENDING"
    CONFIRMED = "CONFIRMED"
    FULFILLING = "FULFILLING"
    PARTIALLY_FULFILLED = "PARTIALLY_FULFILLED"
    FULFILLED = "FULFILLED"
    CANCELLED = "CANCELLED"


class InvoiceStatus(StrEnum):
    DRAFT = "DRAFT"
    ISSUED = "ISSUED"
    PARTIALLY_PAID = "PARTIALLY_PAID"
    PAID = "PAID"
    OVERDUE = "OVERDUE"
    VOID = "VOID"


class PaymentStatus(StrEnum):
    PENDING = "PENDING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    REFUNDED = "REFUNDED"


class BillingInterval(StrEnum):
    MONTHLY = "MONTHLY"
    QUARTERLY = "QUARTERLY"
    YEARLY = "YEARLY"


class SubscriptionStatus(StrEnum):
    TRIAL = "TRIAL"
    ACTIVE = "ACTIVE"
    PAST_DUE = "PAST_DUE"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"


class BillingType(StrEnum):
    ONE_TIME = "ONE_TIME"
    RECURRING = "RECURRING"
    PRORATION = "PRORATION"
    SETUP = "SETUP"


class Severity(StrEnum):
    INFO = "INFO"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class RuleType(StrEnum):
    DISCOUNT = "DISCOUNT"
    APPROVAL = "APPROVAL"
    RISK = "RISK"
    RECOMMENDATION = "RECOMMENDATION"
    ANOMALY = "ANOMALY"
    BLOCK = "BLOCK"


class RuleActionType(StrEnum):
    REQUIRE_APPROVAL = "REQUIRE_APPROVAL"
    RAISE_RISK = "RAISE_RISK"
    RECOMMEND_PRODUCT = "RECOMMEND_PRODUCT"
    BLOCK_QUOTE = "BLOCK_QUOTE"
    REQUIRE_FINANCE = "REQUIRE_FINANCE"
    FLAG_ANOMALY = "FLAG_ANOMALY"


class EventType(StrEnum):
    QUOTE_CREATED = "QUOTE_CREATED"
    QUOTE_UPDATED = "QUOTE_UPDATED"
    LINE_ADDED = "LINE_ADDED"
    LINE_REMOVED = "LINE_REMOVED"
    DISCOUNT_CHANGED = "DISCOUNT_CHANGED"
    RISK_RECALCULATED = "RISK_RECALCULATED"
    APPROVAL_REQUESTED = "APPROVAL_REQUESTED"
    APPROVAL_APPROVED = "APPROVAL_APPROVED"
    APPROVAL_REJECTED = "APPROVAL_REJECTED"
    APPROVAL_CHANGES_REQUESTED = "APPROVAL_CHANGES_REQUESTED"
    RECOMMENDATION_ADDED = "RECOMMENDATION_ADDED"
    WAREHOUSE_OPTIMIZED = "WAREHOUSE_OPTIMIZED"
    CUSTOMER_NEGOTIATED = "CUSTOMER_NEGOTIATED"
    NEGOTIATION_ACCEPTED = "NEGOTIATION_ACCEPTED"
    NEGOTIATION_REJECTED = "NEGOTIATION_REJECTED"
    COUNTEROFFER_GENERATED = "COUNTEROFFER_GENERATED"
    QUOTE_REAPPROVED = "QUOTE_REAPPROVED"
    QUOTE_SENT = "QUOTE_SENT"
    ORDER_CONFIRMED = "ORDER_CONFIRMED"
    INVENTORY_RESERVED = "INVENTORY_RESERVED"
    INVOICE_CREATED = "INVOICE_CREATED"
    PAYMENT_RECEIVED = "PAYMENT_RECEIVED"
    SUBSCRIPTION_CREATED = "SUBSCRIPTION_CREATED"
    OPTIMIZATION_APPLIED = "OPTIMIZATION_APPLIED"
    SIMULATION_APPLIED = "SIMULATION_APPLIED"
    HEALTH_UPDATED = "HEALTH_UPDATED"
    ANOMALY_DETECTED = "ANOMALY_DETECTED"


class ConditionType(StrEnum):
    DISCOUNT_EXCEEDS_TIER = "DISCOUNT_EXCEEDS_TIER"
    MARGIN_BELOW = "MARGIN_BELOW"
    RISK_ABOVE = "RISK_ABOVE"
    DEAL_VALUE_ABOVE = "DEAL_VALUE_ABOVE"
    PAYMENT_TERMS_ABOVE = "PAYMENT_TERMS_ABOVE"
    CATEGORY_DISCOUNT_ABOVE = "CATEGORY_DISCOUNT_ABOVE"
