"""initial schema

Revision ID: b62f14c3396b
Revises: 
Create Date: 2026-09-05 15:25:44.999555
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b62f14c3396b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_chains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_chains'))
    )
    op.create_table('customer_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('default_discount_limit', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('risk_multiplier', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_tiers')),
    sa.UniqueConstraint('name', name=op.f('uq_customer_tiers_name'))
    )
    op.create_table('product_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('kind', sa.Enum('HARDWARE', 'SERVICE', 'SOFTWARE', 'ACCESSORY', 'SUBSCRIPTION', name='categorykind'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_product_categories_name'))
    )
    op.create_table('rule_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rule_type', sa.Enum('DISCOUNT', 'APPROVAL', 'RISK', 'RECOMMENDATION', 'ANOMALY', 'BLOCK', name='ruletype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_definitions'))
    )
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('billing_interval', sa.Enum('MONTHLY', 'QUARTERLY', 'YEARLY', name='billinginterval'), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('setup_fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('trial_days', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_plans'))
    )
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_settings')),
    sa.UniqueConstraint('key', name=op.f('uq_system_settings_key'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SALES_REP', 'SALES_MANAGER', 'FINANCE', 'OPERATIONS', 'CUSTOMER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='fk_users_customer_id_customers', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('shipping_zone', sa.String(length=40), nullable=False),
    sa.Column('handling_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reliability_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('avg_lead_days', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouses')),
    sa.UniqueConstraint('code', name=op.f('uq_warehouses_code'))
    )
    op.create_table('approval_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('approval_chain_id', sa.Integer(), nullable=False),
    sa.Column('condition_type', sa.Enum('DISCOUNT_EXCEEDS_TIER', 'MARGIN_BELOW', 'RISK_ABOVE', 'DEAL_VALUE_ABOVE', 'PAYMENT_TERMS_ABOVE', 'CATEGORY_DISCOUNT_ABOVE', name='conditiontype'), nullable=False),
    sa.Column('condition_value', sa.String(length=80), nullable=False),
    sa.Column('required_role', sa.Enum('SALES_REP', 'SALES_MANAGER', 'FINANCE', 'OPERATIONS', 'CUSTOMER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['approval_chain_id'], ['approval_chains.id'], name=op.f('fk_approval_rules_approval_chain_id_approval_chains')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_rules'))
    )
    op.create_index(op.f('ix_approval_rules_approval_chain_id'), 'approval_rules', ['approval_chain_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('old_value_json', sa.JSON(), nullable=True),
    sa.Column('new_value_json', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('industry', sa.String(length=80), nullable=True),
    sa.Column('customer_tier_id', sa.Integer(), nullable=False),
    sa.Column('credit_limit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_terms', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ON_HOLD', name='customerstatus'), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('sales_rep_id', sa.Integer(), nullable=True),
    sa.Column('avg_accept_days', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('historical_avg_discount', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_tier_id'], ['customer_tiers.id'], name=op.f('fk_customers_customer_tier_id_customer_tiers')),
    sa.ForeignKeyConstraint(['sales_rep_id'], ['users.id'], name='fk_customers_sales_rep_id_users', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    op.create_index(op.f('ix_customers_code'), 'customers', ['code'], unique=True)
    op.create_index(op.f('ix_customers_customer_tier_id'), 'customers', ['customer_tier_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('related_entity_type', sa.String(length=40), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('price_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('customer_tier_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_tier_id'], ['customer_tiers.id'], name=op.f('fk_price_lists_customer_tier_id_customer_tiers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_lists'))
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('product_type', sa.Enum('ONE_TIME', 'SUBSCRIPTION', 'SERVICE', name='producttype'), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('weight', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('subscription_plan_id', sa.Integer(), nullable=True),
    sa.Column('perceived_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], name=op.f('fk_products_category_id_product_categories')),
    sa.ForeignKeyConstraint(['subscription_plan_id'], ['subscription_plans.id'], name=op.f('fk_products_subscription_plan_id_subscription_plans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_product_type'), 'products', ['product_type'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_table('rule_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('REQUIRE_APPROVAL', 'RAISE_RISK', 'RECOMMEND_PRODUCT', 'BLOCK_QUOTE', 'REQUIRE_FINANCE', 'FLAG_ANOMALY', name='ruleactiontype'), nullable=False),
    sa.Column('action_value', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rule_definitions.id'], name=op.f('fk_rule_actions_rule_id_rule_definitions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_actions'))
    )
    op.create_index(op.f('ix_rule_actions_rule_id'), 'rule_actions', ['rule_id'], unique=False)
    op.create_table('rule_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=80), nullable=False),
    sa.Column('operator', sa.String(length=16), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('logical_operator', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rule_definitions.id'], name=op.f('fk_rule_conditions_rule_id_rule_definitions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_conditions'))
    )
    op.create_index(op.f('ix_rule_conditions_rule_id'), 'rule_conditions', ['rule_id'], unique=False)
    op.create_table('discount_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('customer_tier_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('max_discount_percent', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], name=op.f('fk_discount_rules_category_id_product_categories')),
    sa.ForeignKeyConstraint(['customer_tier_id'], ['customer_tiers.id'], name=op.f('fk_discount_rules_customer_tier_id_customer_tiers')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_discount_rules_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discount_rules'))
    )
    op.create_index(op.f('ix_discount_rules_category_id'), 'discount_rules', ['category_id'], unique=False)
    op.create_index(op.f('ix_discount_rules_customer_tier_id'), 'discount_rules', ['customer_tier_id'], unique=False)
    op.create_table('product_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('attributes_json', sa.JSON(), nullable=True),
    sa.Column('price_adjustment', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cost_adjustment', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_variants_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_variants')),
    sa.UniqueConstraint('sku', name=op.f('uq_product_variants_sku'))
    )
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_number', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('sales_rep_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'NEGOTIATING', 'REJECTED', 'CONFIRMED', 'CANCELLED', name='quotestatus'), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('shipping_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cost_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gross_profit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gross_margin_percent', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('deal_health_score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('approval_status', sa.Enum('NOT_REQUIRED', 'PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'CHANGES_REQUESTED', name='approvalstatus'), nullable=False),
    sa.Column('negotiation_status', sa.Enum('NONE', 'OPEN', 'COUNTERED', 'ACCEPTED', 'REJECTED', 'CLOSED', name='negotiationstatus'), nullable=False),
    sa.Column('payment_terms', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('promised_delivery_date', sa.Date(), nullable=True),
    sa.Column('sent_to_customer_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('last_material_change_at', sa.DateTime(), nullable=True),
    sa.Column('shipment_count', sa.Integer(), nullable=False),
    sa.Column('delivery_risk_score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('tax_percent', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_quotes_customer_id_customers')),
    sa.ForeignKeyConstraint(['sales_rep_id'], ['users.id'], name=op.f('fk_quotes_sales_rep_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotes'))
    )
    op.create_index(op.f('ix_quotes_customer_id'), 'quotes', ['customer_id'], unique=False)
    op.create_index(op.f('ix_quotes_quote_number'), 'quotes', ['quote_number'], unique=True)
    op.create_index(op.f('ix_quotes_risk_score'), 'quotes', ['risk_score'], unique=False)
    op.create_index(op.f('ix_quotes_sales_rep_id'), 'quotes', ['sales_rep_id'], unique=False)
    op.create_index(op.f('ix_quotes_status'), 'quotes', ['status'], unique=False)
    op.create_table('recommendation_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('recommended_product_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_type', sa.Enum('UPSELL', 'CROSS_SELL', 'ALTERNATIVE', 'BUNDLE', name='recommendationtype'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=400), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_recommendation_rules_product_id_products')),
    sa.ForeignKeyConstraint(['recommended_product_id'], ['products.id'], name=op.f('fk_recommendation_rules_recommended_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_rules'))
    )
    op.create_index(op.f('ix_recommendation_rules_product_id'), 'recommendation_rules', ['product_id'], unique=False)
    op.create_table('approval_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NOT_REQUIRED', 'PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'CHANGES_REQUESTED', name='approvalstatus'), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('is_reapproval', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], name=op.f('fk_approval_requests_quote_id_quotes')),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_approval_requests_requested_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_requests'))
    )
    op.create_index(op.f('ix_approval_requests_quote_id'), 'approval_requests', ['quote_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_status'), 'approval_requests', ['status'], unique=False)
    op.create_table('deal_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('QUOTE_CREATED', 'QUOTE_UPDATED', 'LINE_ADDED', 'LINE_REMOVED', 'DISCOUNT_CHANGED', 'RISK_RECALCULATED', 'APPROVAL_REQUESTED', 'APPROVAL_APPROVED', 'APPROVAL_REJECTED', 'APPROVAL_CHANGES_REQUESTED', 'RECOMMENDATION_ADDED', 'WAREHOUSE_OPTIMIZED', 'CUSTOMER_NEGOTIATED', 'NEGOTIATION_ACCEPTED', 'NEGOTIATION_REJECTED', 'COUNTEROFFER_GENERATED', 'QUOTE_REAPPROVED', 'QUOTE_SENT', 'ORDER_CONFIRMED', 'INVENTORY_RESERVED', 'INVOICE_CREATED', 'PAYMENT_RECEIVED', 'SUBSCRIPTION_CREATED', 'OPTIMIZATION_APPLIED', 'SIMULATION_APPLIED', 'HEALTH_UPDATED', 'ANOMALY_DETECTED', name='eventtype'), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_deal_events_actor_id_users')),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], name=op.f('fk_deal_events_quote_id_quotes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deal_events'))
    )
    op.create_index(op.f('ix_deal_events_created_at'), 'deal_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_deal_events_quote_id'), 'deal_events', ['quote_id'], unique=False)
    op.create_table('deal_simulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('input_snapshot_json', sa.JSON(), nullable=False),
    sa.Column('result_snapshot_json', sa.JSON(), nullable=False),
    sa.Column('revenue_delta', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('margin_delta', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('risk_delta', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_deal_simulations_created_by_users')),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], name=op.f('fk_deal_simulations_quote_id_quotes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deal_simulations'))
    )
    op.create_index(op.f('ix_deal_simulations_quote_id'), 'deal_simulations', ['quote_id'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('available_qty', sa.Integer(), nullable=False),
    sa.Column('reserved_qty', sa.Integer(), nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=False),
    sa.Column('expected_replenishment', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_inventory_product_id_products')),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name=op.f('fk_inventory_variant_id_product_variants')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_inventory_warehouse_id_warehouses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory')),
    sa.UniqueConstraint('warehouse_id', 'product_id', 'variant_id', name='uq_inventory_wh_prod_var')
    )
    op.create_index(op.f('ix_inventory_product_id'), 'inventory', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_warehouse_id'), 'inventory', ['warehouse_id'], unique=False)
    op.create_table('negotiations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NONE', 'OPEN', 'COUNTERED', 'ACCEPTED', 'REJECTED', 'CLOSED', name='negotiationstatus'), nullable=False),
    sa.Column('last_counteroffer_json', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_negotiations_customer_id_customers')),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], name=op.f('fk_negotiations_quote_id_quotes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_negotiations'))
    )
    op.create_index(op.f('ix_negotiations_customer_id'), 'negotiations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_negotiations_quote_id'), 'negotiations', ['quote_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=32), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'FULFILLING', 'PARTIALLY_FULFILLED', 'FULFILLED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_orders_customer_id_customers')),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], name=op.f('fk_orders_quote_id_quotes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_orders_quote_id'), 'orders', ['quote_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('price_list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price_list_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('min_quantity', sa.Integer(), nullable=False),
    sa.Column('max_quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['price_list_id'], ['price_lists.id'], name=op.f('fk_price_list_items_price_list_id_price_lists')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_price_list_items_product_id_products')),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name=op.f('fk_price_list_items_variant_id_product_variants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_list_items'))
    )
    op.create_index(op.f('ix_price_list_items_price_list_id'), 'price_list_items', ['price_list_id'], unique=False)
    op.create_index(op.f('ix_price_list_items_product_id'), 'price_list_items', ['product_id'], unique=False)
    op.create_table('quote_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gross_profit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('margin_percent', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('subscription_plan_id', sa.Integer(), nullable=True),
    sa.Column('is_freebie', sa.Boolean(), nullable=False),
    sa.Column('source_recommendation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_quote_lines_product_id_products')),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], name=op.f('fk_quote_lines_quote_id_quotes')),
    sa.ForeignKeyConstraint(['subscription_plan_id'], ['subscription_plans.id'], name=op.f('fk_quote_lines_subscription_plan_id_subscription_plans')),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name=op.f('fk_quote_lines_variant_id_product_variants')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_quote_lines_warehouse_id_warehouses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quote_lines'))
    )
    op.create_index(op.f('ix_quote_lines_quote_id'), 'quote_lines', ['quote_id'], unique=False)
    op.create_table('risk_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('factor_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('weight', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], name=op.f('fk_risk_factors_quote_id_quotes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_factors'))
    )
    op.create_index(op.f('ix_risk_factors_quote_id'), 'risk_factors', ['quote_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('TRIAL', 'ACTIVE', 'PAST_DUE', 'CANCELLED', 'EXPIRED', name='subscriptionstatus'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('billing_interval', sa.Enum('MONTHLY', 'QUARTERLY', 'YEARLY', name='billinginterval'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('next_billing_date', sa.Date(), nullable=True),
    sa.Column('mrr', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_subscriptions_customer_id_customers')),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], name=op.f('fk_subscriptions_plan_id_subscription_plans')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_subscriptions_product_id_products')),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], name=op.f('fk_subscriptions_quote_id_quotes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions'))
    )
    op.create_index(op.f('ix_subscriptions_customer_id'), 'subscriptions', ['customer_id'], unique=False)
    op.create_table('approval_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('approval_request_id', sa.Integer(), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.Enum('SALES_REP', 'SALES_MANAGER', 'FINANCE', 'OPERATIONS', 'CUSTOMER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'PENDING', 'APPROVED', 'REJECTED', 'SKIPPED', name='approvalstepstatus'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('acted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_requests.id'], name=op.f('fk_approval_steps_approval_request_id_approval_requests')),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], name=op.f('fk_approval_steps_approver_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_steps'))
    )
    op.create_index(op.f('ix_approval_steps_approval_request_id'), 'approval_steps', ['approval_request_id'], unique=False)
    op.create_table('backorders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('quote_line_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('requested_qty', sa.Integer(), nullable=False),
    sa.Column('available_qty', sa.Integer(), nullable=False),
    sa.Column('backorder_qty', sa.Integer(), nullable=False),
    sa.Column('expected_replenishment', sa.Date(), nullable=True),
    sa.Column('substitute_product_id', sa.Integer(), nullable=True),
    sa.Column('alternative_warehouse_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alternative_warehouse_id'], ['warehouses.id'], name=op.f('fk_backorders_alternative_warehouse_id_warehouses')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_backorders_product_id_products')),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], name=op.f('fk_backorders_quote_id_quotes')),
    sa.ForeignKeyConstraint(['quote_line_id'], ['quote_lines.id'], name=op.f('fk_backorders_quote_line_id_quote_lines')),
    sa.ForeignKeyConstraint(['substitute_product_id'], ['products.id'], name=op.f('fk_backorders_substitute_product_id_products')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_backorders_warehouse_id_warehouses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backorders'))
    )
    op.create_index(op.f('ix_backorders_quote_id'), 'backorders', ['quote_id'], unique=False)
    op.create_table('fulfillment_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('quote_line_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('delivery_days', sa.Integer(), nullable=False),
    sa.Column('is_backorder', sa.Boolean(), nullable=False),
    sa.Column('is_recommended', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_fulfillment_allocations_product_id_products')),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], name=op.f('fk_fulfillment_allocations_quote_id_quotes')),
    sa.ForeignKeyConstraint(['quote_line_id'], ['quote_lines.id'], name=op.f('fk_fulfillment_allocations_quote_line_id_quote_lines')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_fulfillment_allocations_warehouse_id_warehouses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fulfillment_allocations'))
    )
    op.create_index(op.f('ix_fulfillment_allocations_quote_id'), 'fulfillment_allocations', ['quote_id'], unique=False)
    op.create_table('inventory_reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('RESERVED', 'RELEASED', 'FULFILLED', name='reservationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_inventory_reservations_order_id_orders')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_inventory_reservations_product_id_products')),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], name=op.f('fk_inventory_reservations_quote_id_quotes')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_inventory_reservations_warehouse_id_warehouses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_reservations'))
    )
    op.create_index(op.f('ix_inventory_reservations_quote_id'), 'inventory_reservations', ['quote_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'VOID', name='invoicestatus'), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('balance_due', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_invoices_customer_id_customers')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_invoices_order_id_orders')),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], name=op.f('fk_invoices_quote_id_quotes')),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('fk_invoices_subscription_id_subscriptions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices'))
    )
    op.create_index(op.f('ix_invoices_customer_id'), 'invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_table('negotiation_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negotiation_id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=True),
    sa.Column('request_type', sa.Enum('DISCOUNT', 'QUANTITY', 'PRODUCT_CHANGE', 'LINE_REJECT', 'ALTERNATIVE', 'PAYMENT_TERMS', 'COMMENT', 'ACCEPT_RECOMMENDATION', 'COUNTEROFFER', name='negotiationrequesttype'), nullable=False),
    sa.Column('old_value', sa.String(length=255), nullable=True),
    sa.Column('requested_value', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'COUNTERED', 'CANCELLED', name='requeststatus'), nullable=False),
    sa.Column('margin_impact', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('risk_impact', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('exception_percent', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('counteroffer_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('acted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['acted_by'], ['users.id'], name=op.f('fk_negotiation_requests_acted_by_users')),
    sa.ForeignKeyConstraint(['line_id'], ['quote_lines.id'], name=op.f('fk_negotiation_requests_line_id_quote_lines')),
    sa.ForeignKeyConstraint(['negotiation_id'], ['negotiations.id'], name=op.f('fk_negotiation_requests_negotiation_id_negotiations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_negotiation_requests'))
    )
    op.create_index(op.f('ix_negotiation_requests_negotiation_id'), 'negotiation_requests', ['negotiation_id'], unique=False)
    op.create_table('invoice_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('billing_type', sa.Enum('ONE_TIME', 'RECURRING', 'PRORATION', 'SETUP', name='billingtype'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_lines_invoice_id_invoices')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_invoice_lines_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_lines'))
    )
    op.create_index(op.f('ix_invoice_lines_invoice_id'), 'invoice_lines', ['invoice_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('reference', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_payments_invoice_id_invoices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_invoice_lines_invoice_id'), table_name='invoice_lines')
    op.drop_table('invoice_lines')
    op.drop_index(op.f('ix_negotiation_requests_negotiation_id'), table_name='negotiation_requests')
    op.drop_table('negotiation_requests')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_customer_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_inventory_reservations_quote_id'), table_name='inventory_reservations')
    op.drop_table('inventory_reservations')
    op.drop_index(op.f('ix_fulfillment_allocations_quote_id'), table_name='fulfillment_allocations')
    op.drop_table('fulfillment_allocations')
    op.drop_index(op.f('ix_backorders_quote_id'), table_name='backorders')
    op.drop_table('backorders')
    op.drop_index(op.f('ix_approval_steps_approval_request_id'), table_name='approval_steps')
    op.drop_table('approval_steps')
    op.drop_index(op.f('ix_subscriptions_customer_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_risk_factors_quote_id'), table_name='risk_factors')
    op.drop_table('risk_factors')
    op.drop_index(op.f('ix_quote_lines_quote_id'), table_name='quote_lines')
    op.drop_table('quote_lines')
    op.drop_index(op.f('ix_price_list_items_product_id'), table_name='price_list_items')
    op.drop_index(op.f('ix_price_list_items_price_list_id'), table_name='price_list_items')
    op.drop_table('price_list_items')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_quote_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_negotiations_quote_id'), table_name='negotiations')
    op.drop_index(op.f('ix_negotiations_customer_id'), table_name='negotiations')
    op.drop_table('negotiations')
    op.drop_index(op.f('ix_inventory_warehouse_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_product_id'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_deal_simulations_quote_id'), table_name='deal_simulations')
    op.drop_table('deal_simulations')
    op.drop_index(op.f('ix_deal_events_quote_id'), table_name='deal_events')
    op.drop_index(op.f('ix_deal_events_created_at'), table_name='deal_events')
    op.drop_table('deal_events')
    op.drop_index(op.f('ix_approval_requests_status'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_quote_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_recommendation_rules_product_id'), table_name='recommendation_rules')
    op.drop_table('recommendation_rules')
    op.drop_index(op.f('ix_quotes_status'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_sales_rep_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_risk_score'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_quote_number'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_customer_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index(op.f('ix_discount_rules_customer_tier_id'), table_name='discount_rules')
    op.drop_index(op.f('ix_discount_rules_category_id'), table_name='discount_rules')
    op.drop_table('discount_rules')
    op.drop_index(op.f('ix_rule_conditions_rule_id'), table_name='rule_conditions')
    op.drop_table('rule_conditions')
    op.drop_index(op.f('ix_rule_actions_rule_id'), table_name='rule_actions')
    op.drop_table('rule_actions')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_product_type'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_table('products')
    op.drop_table('price_lists')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_customers_customer_tier_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_code'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_approval_rules_approval_chain_id'), table_name='approval_rules')
    op.drop_table('approval_rules')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_settings')
    op.drop_table('subscription_plans')
    op.drop_table('rule_definitions')
    op.drop_table('product_categories')
    op.drop_table('customer_tiers')
    op.drop_table('approval_chains')
    # ### end Alembic commands ###
